spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/querydsl
    username: root
    password: admin
  jpa:
    show-sql : true
    hibernate:
      format_sql : true
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:8080
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope: profile,email
            #redirect_uri: http://localhost:8080/oauth2/callback/google

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace