spring:
  datasource:
    url: jdbc:mysql://database-toy.crycms26uxwe.us-east-2.rds.amazonaws.com:3306/toy
    username: admin
    password: mysqladmin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql : true
    hibernate:
      format_sql : true
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace