spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql : true
    hibernate:
      format_sql : true
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  profiles:
    include: oauth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${client.id}
            client-secret: ${client.secret}
            scope: profile,email
            redirect-uri: ${redirect_uri}
        jwt:
          secret: ${JWT_SECRET}
          expiration: 86400000 # JWT 토큰의 유효 기간 (밀리초 단위) 24시간
          token-prefix: Bearer  # 토큰의 헤더 이름
          header: Authorization # 토큰의 헤더에 저장될 키
          algorithm: HS512
          #issuer-uri: https://localhost:8080

#Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    #groups-order: ASC

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace