spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/querydsl
    username: root
    password: admin
  jpa:
    show-sql : true
    hibernate:
      format_sql : true
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://your-authorization-server.com
      client:
        registration:
          google:
            client-id: YOUR_CLIENT_ID
            client-secret: YOUR_CLIENT_SECRET
            scope: profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://www.googleapis.com/oauth2/v3/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: name

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace