version: '3.8'

services:
  web:
    image: devjm95/web-app:latest
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=${{ secrets.DATABASE_URL }}
      - DATABASE_USER=${{ secrets.DATABASE_USERNAME }}
      - DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

  my_service:
    image: devjm95/my-repo:latest
    environment:
      - jwt.secret= ${{ secrets.JWT_SECRET}}
      -
volumes:
  db_data: